name: Terraform Lint Check

# Run this workflow on push or pull request events targeting the master branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  terraform-lint:
    name: Terraform Lint
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      # Install tflint (Terraform Linter)
      - name: Install tflint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash

      # Run tflint on the code
      - name: Run tflint
        run: |
          tflint

      # If tflint fails, the job will fail and prevent the commit/merge